# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0014_auto_20170309_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagemodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='название')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='рейтинг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categorymodel')),
            ],
        ),
    ]
