# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_imagemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата загрузки изображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='название'),
        ),
    ]
