# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170314_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='author',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
