# Generated by Django 2.0.4 on 2018-05-24 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180504_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_orig',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images_orig'),
            preserve_default=False,
        ),
    ]
