# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(height_field=250, upload_to='upload/', verbose_name='картинка категории', width_field=375)),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата создания категории')),
            ],
        ),
        migrations.CreateModel(
            name='Imagemodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='название')),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='рейтинг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categorymodel')),
            ],
        ),
    ]
