# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование категории')),
                ('pic', models.ImageField(height_field=250, upload_to='upload/', verbose_name='Картинка для категории', width_field=375)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания категории')),
            ],
        ),
    ]
