# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Category creation date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(height_field=250, upload_to='upload/', verbose_name='Category pic', width_field=375),
        ),
    ]
