# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170301_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, height_field=250, upload_to='upload', verbose_name='картинка категории', width_field=375),
        ),
    ]
