# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170302_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.FileField(upload_to='user', verbose_name='картинка категории'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(blank=True, upload_to='user'),
        ),
    ]
