# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170302_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='Imagemodel',
        ),
    ]
