# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170301_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата загрузки изображения'),
            preserve_default=False,
        ),
    ]
