# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170302_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(upload_to='upload', verbose_name='картинка категории'),
        ),
    ]
