# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbyname', models.CharField(max_length=32, verbose_name='Хобби')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Образцы работ')),
                ('hobbylevel', models.CharField(max_length=16, verbose_name='Сила увлечения')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.CharField(max_length=32, verbose_name='Наименование учебного учреждения')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт Учреждения')),
                ('course', models.CharField(max_length=16, verbose_name='Курс/Специальность')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Длительность обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=32, verbose_name='Организация')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('position', models.CharField(max_length=16, verbose_name='Должность')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Время работы')),
            ],
        ),
    ]
